admins/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import LoginView

app_name = "admins"

urlpatterns = [


    path('index', index, name='index'),

    path('', LoginView.as_view(redirect_authenticated_user=True), name="login"),

    #signup_manager
    path('signup_manager', signup_manager, name='signup_manager'),
    #signup_worker
    path('signup_worker', signup_worker, name='signup_worker'),
    #dashboard
    path('dashboard', dashboard, name='dashboard'),



    #Create Manager
    path('create_manager', create_manager, name='create_manager'),
    # Edit Manager
    url(r'^edit_manager/(?P<id>\d+)/$', edit_manager, name='edit_manager'),
    # Delete Manager
    url(r'^delete_manager/(?P<id>\d+)/$', delete_manager, name='delete_manager'),


    #Create Worker
    path('create_worker', create_worker, name='create_worker'),
    # Edit Worker
    url(r'^edit_worker/(?P<id>\d+)/$', edit_worker, name='edit_worker'),
    # Delete Worker
    url(r'^delete_worker/(?P<id>\d+)/$', delete_worker, name='delete_worker'),



    #Create Departament
    path('create_departament', create_departament, name='create_departament'),
    # Edit Manager
    url(r'^edit_departament/(?P<id>\d+)/$', edit_departament, name='edit_departament'),
    # Delete Departament
    url(r'^delete_departament/(?P<id>\d+)/$', delete_departament, name='delete_departament'),

    

    #List Manager
    path('list_manager', list_manager, name='list_manager'),
    #List Worker
    path('list_worker', list_worker, name='list_worker'),
    #List Departament
    path('list_departament', list_departament, name='list_departament'),


]

manager/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from .views import *

app_name = "manager"

urlpatterns = [

    # My Tasks
    path('my_task/', my_task, name='my_task'),
     # My Workers
    path('my_works/', my_works, name='my_works'),
    # Create Task
    path('create_task/', create_task, name='create_task'),
    # Edit Manager
    url(r'^edit_task/(?P<id>\d+)/$', edit_task, name='edit_task'),
    # Delete Manager
    url(r'^delete_task/(?P<id>\d+)/$', delete_task, name='delete_task'),

    #reports
    path('reports/', reports, name='reports'),
    # Edit Manager
    url(r'^edit_report/(?P<id>\d+)/$', edit_report, name='edit_report'),

    #profile
    path('edit_profile/', edit_profile, name='edit_profile'),


]

pruebas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    
    path('', include('admins.urls')),

    path('manager/', include('manager.urls')),

    path('worker/', include('worker.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worker/urls.py
from . import views
from django.conf.urls import url
from .views import *
from django.urls import path, include

app_name = "worker"

urlpatterns = [


    #Look Tasks
    path('my_tasks', my_tasks, name='my_tasks'),
    # Finish Task
    url(r'^finish_task/(?P<id>\d+)/$', finish_task, name='finish_task'),

    # Create Report
    path('create_report', create_report, name='create_report'),
    # My report
    path('my_report', my_report, name='my_report'),

    # My profile
    path('profile_worker', profile_worker, name='profile_worker'),
   


]

manager/models.py
from django.db import models
from .validators import validate_file_size
from phone_field import PhoneField
from admins.models import User


class Managers(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    profile_picture = models.ImageField(upload_to='avatar/manager/%Y/%m/%d', default='avatar/default.jpg',
                                 verbose_name='avatar', null=True, blank=True, validators=[validate_file_size])
    ## 
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = PhoneField(blank=True)
    # 
    is_active = models.BooleanField(default = False)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Departament(models.Model):

    name = models.CharField(max_length=50)
    responsible = models.OneToOneField(Managers, on_delete=models.CASCADE, primary_key=True)
    create_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

worker/models.py
from django.db import models
from manager.models import Managers, Departament, User
from manager.validators import validate_file_size
from phone_field import PhoneField

class Worker(models.Model):
    manager = models.ForeignKey(Managers, on_delete=models.CASCADE)
    departament = models.ForeignKey(Departament, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    is_active = models.BooleanField(default = False)
    profile_picture = models.ImageField(upload_to='avatar/worker/%Y/%m/%d', default='avatar/default.jpg',
                                 verbose_name='avatar', null=True, blank=True, validators=[validate_file_size])
    ## 
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = PhoneField(blank=True)
    
    def __str__(self):
        return self.first_name + ' ' + self.last_name
    
class Task(models.Model):
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    asign = models.ForeignKey(Managers, on_delete=models.CASCADE)
    #task description
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    #dates
    start_date = models.DateField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    end_date = models.DateField(blank=True, null=True)
    #status
    is_finish = models.BooleanField(default = False)

    def task_complete(self):

        task = Task.objects.filter(worker=self.worker, is_finish=True).count()
        return str(task)
    
    def task_pending(self):

        task = Task.objects.filter(worker=self.worker, is_finish=False).count()
        return str(task)

class Report(models.Model):
    date = models.DateField(auto_now_add=True)
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    observation = models.CharField(max_length=200, blank=True, null=True)

manager/forms.py
from .models import Managers, Departament
from django import forms

class ManagersRegistroForm(forms.ModelForm):

    class Meta:
        model = Managers
        fields = '__all__'
        exclude = ['user', 'is_active']

class DepartamentForm(forms.ModelForm):

    class Meta:
        model = Departament
        fields = '__all__'
        

worker/forms.py
from .models import Worker, Task, Report
from django import forms
from manager.models import Managers


class WorkerRegistroForm(forms.ModelForm):

    class Meta:
        model = Worker
        fields = '__all__'
        exclude = ['user', 'is_active']

class WorkerUpdateForm(forms.ModelForm):

    class Meta:
        model = Worker
        fields = '__all__'
        exclude = ['user', 'is_active', 'departament', 'manager']

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__'
        exclude = ['asign']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(TaskForm, self).__init__(*args, **kwargs)
        manager = Managers.objects.get(user=user)
        self.fields['worker'].queryset = Worker.objects.filter(manager=manager)    

class OtherTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['is_finish']
        exclude = ['asign']

class ReportForm(forms.ModelForm):

    class Meta:
        model = Report
        fields = '__all__'
        exclude = ['worker', 'observation']


class ReportUpdateForm(forms.ModelForm):

    class Meta:
        model = Report
        fields = '__all__'
        exclude = ['worker']

        

manager/views.py
from django.shortcuts import render, redirect
from admins.models import User
from django.contrib import messages
from manager.models import Managers, Departament
from django.http import HttpResponseRedirect
from worker.models import *
from worker.forms import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#List Task
def my_task(request):

    manager = Managers.objects.get(user=request.user)
    task = Task.objects.filter(asign=manager)

    return render(request, 'manager/task.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#Create Task
def create_task(request):

    manager = Managers.objects.get(user=request.user)

    if request.method == 'POST':
        form = TaskForm(request.POST, user=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.asign = manager
            user.save()  
            messages.success(request, 'Task has been created successfully')
            return redirect('manager:my_task')
    else:
        form = TaskForm(user=request.user)
    
    return render(request, 'manager/create_task.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#Edit Task
def edit_task(request, id):

    manager = Managers.objects.get(user=request.user)
    task = Task.objects.get(id=id)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task, user=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.asign = manager
            user.save()  
            messages.success(request, 'Task has been created successfully')
            return redirect('manager:my_task')
    else:
        form = TaskForm(instance=task, user=request.user)
    
    return render(request, 'manager/create_task.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
# Delete Task
def delete_task(request, id):

    try:
        task = Task.objects.get(id=id)
    except Task.DoesNotExist:
        raise Http404("Task Doesn't exist")
    task.delete()
    messages.success(request, 'Task Delete successfullt!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#List my Works
def my_works(request):

    manager = Managers.objects.get(user=request.user)

    workers = Worker.objects.filter(manager=manager)

    return render(request, 'manager/workers.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#Edit my profile
def my_works(request):

    manager = Managers.objects.get(user=request.user)

    workers = Worker.objects.filter(manager=manager)

    return render(request, 'manager/workers.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#Reports
def reports(request):

    manager = Managers.objects.get(user=request.user)

    workers = Worker.objects.filter(manager=manager)

    report = Report.objects.filter(worker__in=workers)

    return render(request, 'manager/reports.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#edit report
def edit_report(request, id):

    report = Report.objects.get(id=id)

    if request.method == 'POST':
        form = ReportUpdateForm(request.POST, instance=report)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()  
            messages.success(request, 'Report has been update successfully')
            return redirect('manager:reports')
    else:
        form = ReportUpdateForm(instance=report)
 
    return render(request, 'manager/report_edit.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#edit profile
def edit_profile(request):

    profile = Managers.objects.get(user=request.user)

    if request.method == 'POST':
        form = ManagersRegistroForm(request.POST, instance=profile)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()  
            messages.success(request, 'Report has been update successfully')
            return redirect('manager:reports')
    else:
        form = ManagersRegistroForm(instance=profile)
 
    return render(request, 'manager/profile.html', locals())

worker/views.py
from django.shortcuts import render, redirect
from admins.models import User
from django.contrib import messages
from manager.models import Managers, Departament
from django.http import HttpResponseRedirect
from worker.models import *
from worker.forms import *
import datetime
from datetime import datetime, time, date, timedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#task by worker
def my_tasks(request):

    worker = Worker.objects.get(user=request.user)
    task = Task.objects.filter(worker=worker)

    if task:

        porcen_complete = Task.objects.filter(worker=worker, is_finish=True)
        num_complete = porcen_complete.count() * 100 / task.count() 

        porcent_incomplete = Task.objects.filter(worker=worker, is_finish=False)
        num_incomplete = porcent_incomplete.count() * 100 / task.count()

        diference = (porcen_complete.count() -  porcent_incomplete.count()) * 100 / task.count() 

        diference_two = (porcent_incomplete.count() - porcen_complete.count()) * 100 / task.count()
    
    else:
        num_complete = 0
        num_incomplete = 0
        diference = 0
        diference_two = 0


    return render(request, 'worker/task.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#finish task by worker
def finish_task(request, id):
    task = Task.objects.get(id=id)
    today = date.today()

    if request.method == 'POST':
        form = OtherTaskForm(request.POST, instance=task)
        if form.is_valid():
            user = form.save(commit=False)
            user.end_date = today
            user.save()  
            messages.success(request, 'Task has been update successfully')
            return redirect('worker:my_tasks')
    else:
        form = OtherTaskForm(instance=task)
 
    return render(request, 'worker/modal.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#create report / worker
def create_report(request):

    worker = Worker.objects.get(user=request.user)

    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.worker = worker
            user.save()  
            messages.success(request, 'Report has been created successfully')
            return redirect('worker:my_report')
    else:
        form = ReportForm()
 
    return render(request, 'worker/report/create_report.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#list of report by worker
def my_report(request):

    worker = Worker.objects.get(user=request.user)

    report = Report.objects.filter(worker=worker)

    return render(request, 'worker/report/my_report.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#edit profile worker
def profile_worker(request):

    worker = Worker.objects.get(user=request.user)

    if request.method == 'POST':
        form = WorkerUpdateForm(request.POST, instance=worker)
        if form.is_valid():
            user = form.save(commit=False)
            user.worker = worker
            user.save()  
            messages.success(request, 'Profile has been update successfully')
            return redirect('worker:my_report')
    else:
        form = WorkerUpdateForm(instance=worker)
 
    return render(request, 'worker/profile.html', locals())


    

templates/manager/create_task.html
{% extends "bases/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="breadcrumb-area">
    <h1>Create Task</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:dashboard' %}"><i class='bx bx-task'></i></a></li>

        <li class="item">Task</li>

        {% if task %}
        <li class="item">Edit Task</li>
        {% else %}
        <li class="item">Add Task</li>
        {% endif %}
    </ol>
</div>

<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">

        {% if task %}
        <h3>Update Task</h3>
        {% else %}
        <h3>Add Task</h3>
        {% endif %}
        
    </div>

    {% if form.errors  %}
    <br>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ form.errors }} </strong>
    </div>
    {% endif %}
    
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% if task %}
            <div class="form-group">
               {{ form.name|as_crispy_field }}
            </div>

            <div class="form-group">
               {{ form.description|as_crispy_field }}
            </div>

            <div class="form-group">
                {{ form.worker|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ form.is_finish|as_crispy_field }}
            </div>
          
            <button type="submit" class="btn btn-primary">Edit</button>
            {% else %}
            <div class="form-group">
               {{ form.name|as_crispy_field }}
            </div>

            <div class="form-group">
               {{ form.description|as_crispy_field }}
            </div>

            <div class="form-group">
                {{ form.worker|as_crispy_field }}
            </div>
          
            
            <button type="submit" class="btn btn-primary">Create</button>
            {% endif %}
        </form>

    </div>
</div>


{% endblock %}

templates/manager/profile.html
{% extends "bases/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="breadcrumb-area">
    <h1>Edit Profile</h1>

</div>

<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">

        <h3>Edit Profile</h3>
        
    </div>

    {% if form.errors  %}
    <br>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ form.errors }} </strong>
    </div>
    {% endif %}
    
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

           
            <div class="form-group">
               {{ form|crispy }}
            </div>

          
            <button type="submit" class="btn btn-primary">Update</button>
        </form>

    </div>
</div>


{% endblock %}

templates/manager/report_edit.html
{% extends "bases/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="breadcrumb-area">
    <h1>Edit Report</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:dashboard' %}"><i class='bx bxs-report'></i></a></li>

        <li class="item">Report</li>

        <li class="item">Edit Report</li>
    </ol>
</div>

<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">

        <h3>Edit Report</h3>
        
    </div>

    {% if form.errors  %}
    <br>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ form.errors }} </strong>
    </div>
    {% endif %}
    
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

           
            <div class="form-group">
               {{ form|crispy }}
            </div>

          
            <button type="submit" class="btn btn-primary">Create</button>
        </form>

    </div>
</div>


{% endblock %}

templates/manager/reports.html
{% extends "bases/base.html" %}


{% block content %}

<div class="breadcrumb-area">
    <h1>Report</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:dashboard' %}"><i class='bx bxs-report'></i></a></li>

        <li class="item">Report</li>

    </ol>
</div>


<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h3>All Reports</h3>

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}  </strong>
            </div>
            {% endfor %}

        
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Worker</th>
                        <th scope="col">Created</th>
                        <th scope="col">Description</th>
                        <th scope="col">Observation</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in report %}
                    <tr>
                        <th scope="row">{{ forloop.counter }} </th>
                        <td>{{ x.worker }}</td>
                        <td>{{ x.date }}</td>
                        <td>{{ x.description }}</td>
                        {% if x.observation %}
                        <td>{{ x.observation }}</td>
                        {% else %}
                        <td>No observations</td>
                        {% endif %}
                        <td><a href="{% url 'manager:edit_report' x.id %}"  data-toggle="tooltip" data-placement="bottom" title="Edit">
                                <i class="bx bxs-edit"></i>
                            </a></td>
                    </tr>
                    {% endfor %}
                   
                </tbody>
            </table>
        </div>

    </div>
</div>
<!-- End -->



{% endblock %}

templates/manager/task.html
{% extends "bases/base.html" %}


{% block content %}

<div class="breadcrumb-area">
    <h1>Task</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:dashboard' %}"><i class='bx bxs-user-pin'></i></a></li>

        <li class="item">Task</li>

        <li class="item">My Tasks</li>
    </ol>
</div>


<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h3>All Tasks</h3>

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}  </strong>
            </div>
            {% endfor %}

        
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Worker</th>
                        <th scope="col">Name Task</th>
                        <th scope="col">Description Task</th>
                        <th scope="col">Start date</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in task %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}   <img src="{{ x.worker.profile_picture.url }}" width="30" height="30" class="rounded-circle" alt="image"></th>
                        <td>{{ x.worker }}</td>
                        <td>{{ x.name }}</td>
                        <td>{{ x.description }}</td>
                        <td>{{ x.start_date }}</td>
                        {% if x.is_finish == True %}
                        <td>is finished</td>
                        {% else %}
                        <th>in process</td>
                        {% endif %}
                        <td> 
                            <a href="{% url 'manager:edit_task' x.id %}"  data-toggle="tooltip" data-placement="bottom" title="Edit">
                                <i class="bx bxs-edit"></i>
                            </a>
                            
                            <a href="{% url 'manager:delete_task' x.id %}" onclick="return confirm('Are you sure of delete this Task?');"  data-toggle="tooltip" data-placement="bottom" title="Delete">
                                <i class="bx bxs-trash"></i>
                            </a>
                        
                        
                        </td>
                    </tr>
                    {% endfor %}
                   
                </tbody>
            </table>
        </div>

    </div>
</div>
<!-- End -->



{% endblock %}

templates/manager/workers.html
{% extends "bases/base.html" %}


{% block content %}

<div class="breadcrumb-area">
    <h1>Worker</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:dashboard' %}"><i class='bx bxs-user-pin'></i></a></li>

        <li class="item">Worker</li>

        <li class="item">My Workers</li>
    </ol>
</div>


<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h3>All Workers</h3>

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}  </strong>
            </div>
            {% endfor %}

        
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Worker</th>
                        <th scope="col">Names</th>
                        <th scope="col">Departament</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Status</th>
                        <th scope="col">Tasks completed</th>
                        <th scope="col">Pending tasks</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in workers %}
                    <tr>
                        <th scope="row">{{ forloop.counter }} </th>
                        <td>{{ x.user }}</td>
                        <td>{{ x }}</td>
                        <td>{{ x.departament }}</td>
                        <td>{{ x.phone }}</td>
                        {% if x.is_active == True %}
                        <td>is Active</td>
                        {% else %}
                        <th>Without Activity</td>
                        {% endif %}
                        
                        {% for y in x.task_set.all %} 
                        {% if forloop.last %}   
                        <td>   {{ y.task_complete }} </td> 
                         <td>{{ y.task_pending }}</td> 

                         {% endif %}
                         {% endfor %}
                        
                        

                        

                        


                    </tr>
                    {% endfor %}
                   
                </tbody>
            </table>
        </div>

    </div>
</div>
<!-- End -->



{% endblock %}