admins/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import LoginView

app_name = "admins"

urlpatterns = [


    path('index', index, name='index'),

    path('', LoginView.as_view(redirect_authenticated_user=True), name="login"),

    #signup_manager
    path('signup_manager', signup_manager, name='signup_manager'),
    #signup_worker
    path('signup_worker', signup_worker, name='signup_worker'),
    #dashboard
    path('dashboard', dashboard, name='dashboard'),



    #Create Manager
    path('create_manager', create_manager, name='create_manager'),
    # Edit Manager
    url(r'^edit_manager/(?P<id>\d+)/$', edit_manager, name='edit_manager'),
    # Delete Manager
    url(r'^delete_manager/(?P<id>\d+)/$', delete_manager, name='delete_manager'),


    #Create Worker
    path('create_worker', create_worker, name='create_worker'),
    # Edit Worker
    url(r'^edit_worker/(?P<id>\d+)/$', edit_worker, name='edit_worker'),
    # Delete Worker
    url(r'^delete_worker/(?P<id>\d+)/$', delete_worker, name='delete_worker'),



    #Create Departament
    path('create_departament', create_departament, name='create_departament'),
    # Edit Manager
    url(r'^edit_departament/(?P<id>\d+)/$', edit_departament, name='edit_departament'),
    # Delete Departament
    url(r'^delete_departament/(?P<id>\d+)/$', delete_departament, name='delete_departament'),

    

    #List Manager
    path('list_manager', list_manager, name='list_manager'),
    #List Worker
    path('list_worker', list_worker, name='list_worker'),
    #List Departament
    path('list_departament', list_departament, name='list_departament'),


]

manager/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from .views import *

app_name = "manager"

urlpatterns = [

    # My Tasks
    path('my_task/', my_task, name='my_task'),
     # My Workers
    path('my_works/', my_works, name='my_works'),
    # Create Task
    path('create_task/', create_task, name='create_task'),
    # Edit Manager
    url(r'^edit_task/(?P<id>\d+)/$', edit_task, name='edit_task'),
    # Delete Manager
    url(r'^delete_task/(?P<id>\d+)/$', delete_task, name='delete_task'),

    #reports
    path('reports/', reports, name='reports'),
    # Edit Manager
    url(r'^edit_report/(?P<id>\d+)/$', edit_report, name='edit_report'),

    #profile
    path('edit_profile/', edit_profile, name='edit_profile'),


]

pruebas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    
    path('', include('admins.urls')),

    path('manager/', include('manager.urls')),

    path('worker/', include('worker.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/models.py
from django.db import models
from .validators import validate_file_size
from phone_field import PhoneField
from admins.models import User


class Managers(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    profile_picture = models.ImageField(upload_to='avatar/manager/%Y/%m/%d', default='avatar/default.jpg',
                                 verbose_name='avatar', null=True, blank=True, validators=[validate_file_size])
    ## 
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = PhoneField(blank=True)
    # 
    is_active = models.BooleanField(default = False)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Departament(models.Model):

    name = models.CharField(max_length=50)
    responsible = models.OneToOneField(Managers, on_delete=models.CASCADE, primary_key=True)
    create_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

manager/forms.py
from .models import Managers, Departament
from django import forms

class ManagersRegistroForm(forms.ModelForm):

    class Meta:
        model = Managers
        fields = '__all__'
        exclude = ['user', 'is_active']

class DepartamentForm(forms.ModelForm):

    class Meta:
        model = Departament
        fields = '__all__'
        

manager/views.py
from django.shortcuts import render, redirect
from admins.models import User
from django.contrib import messages
from manager.models import Managers, Departament
from django.http import HttpResponseRedirect
from worker.models import *
from worker.forms import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#List Task
def my_task(request):

    manager = Managers.objects.get(user=request.user)
    task = Task.objects.filter(asign=manager)

    return render(request, 'manager/task.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#Create Task
def create_task(request):

    manager = Managers.objects.get(user=request.user)

    if request.method == 'POST':
        form = TaskForm(request.POST, user=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.asign = manager
            user.save()  
            messages.success(request, 'Task has been created successfully')
            return redirect('manager:my_task')
    else:
        form = TaskForm(user=request.user)
    
    return render(request, 'manager/create_task.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#Edit Task
def edit_task(request, id):

    manager = Managers.objects.get(user=request.user)
    task = Task.objects.get(id=id)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task, user=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.asign = manager
            user.save()  
            messages.success(request, 'Task has been created successfully')
            return redirect('manager:my_task')
    else:
        form = TaskForm(instance=task, user=request.user)
    
    return render(request, 'manager/create_task.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
# Delete Task
def delete_task(request, id):

    try:
        task = Task.objects.get(id=id)
    except Task.DoesNotExist:
        raise Http404("Task Doesn't exist")
    task.delete()
    messages.success(request, 'Task Delete successfullt!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#List my Works
def my_works(request):

    manager = Managers.objects.get(user=request.user)

    workers = Worker.objects.filter(manager=manager)

    return render(request, 'manager/workers.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#Edit my profile
def my_works(request):

    manager = Managers.objects.get(user=request.user)

    workers = Worker.objects.filter(manager=manager)

    return render(request, 'manager/workers.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#Reports
def reports(request):

    manager = Managers.objects.get(user=request.user)

    workers = Worker.objects.filter(manager=manager)

    report = Report.objects.filter(worker__in=workers)

    return render(request, 'manager/reports.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#edit report
def edit_report(request, id):

    report = Report.objects.get(id=id)

    if request.method == 'POST':
        form = ReportUpdateForm(request.POST, instance=report)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()  
            messages.success(request, 'Report has been update successfully')
            return redirect('manager:reports')
    else:
        form = ReportUpdateForm(instance=report)
 
    return render(request, 'manager/report_edit.html', locals())

@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_manager, login_url='admins:dashboard')
#edit profile
def edit_profile(request):

    profile = Managers.objects.get(user=request.user)

    if request.method == 'POST':
        form = ManagersRegistroForm(request.POST, instance=profile)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()  
            messages.success(request, 'Report has been update successfully')
            return redirect('manager:reports')
    else:
        form = ManagersRegistroForm(instance=profile)
 
    return render(request, 'manager/profile.html', locals())

templates/admins/manager/create_manager.html
{% extends "bases/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="breadcrumb-area">
    <h1>Manager</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:index' %}"><i class='bx bxs-user-pin'></i></a></li>

        <li class="item">Manager</li>

        {% if manager_user %}
        <li class="item">Edit Manager</li>
        {% else %}
        <li class="item">Add Manager</li>
        {% endif %}
    </ol>
</div>

<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">

        {% if manager_user %}
        <h3>Update Manager</h3>
        {% else %}
        <h3>Add Manager</h3>
        {% endif %}
        
    </div>

    {% if user_form.errors or manager_form.errors  %}
    <br>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ user_form.errors }} </strong>
        <strong>{{ manager_form.errors }} </strong>
    </div>
    {% endif %}
    
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% if manager_user %}
            <div class="form-group">
                {{ manager_form.first_name|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ manager_form.last_name|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ manager_form.phone|as_crispy_field }}
            </div>

            {% else %}

            <div class="form-group">
                {{ user_form.username|as_crispy_field }}
              
            </div>
            <div class="form-group">
                {{ user_form.password1|as_crispy_field }}
              
            </div>
            <div class="form-group">
                {{ user_form.password2|as_crispy_field }}
              
            </div>
            <div class="form-group">
                {{ manager_form.first_name|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ manager_form.last_name|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ manager_form.phone|as_crispy_field }}
            </div>

            {% endif %}

            <button type="submit" class="btn btn-primary">Update</button>
        </form>

    </div>
</div>


{% endblock %}

templates/admins/manager/list_manager.html
{% extends "bases/base.html" %}


{% block content %}

<div class="breadcrumb-area">
    <h1>Manager</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:dashboard' %}"><i class='bx bxs-user-pin'></i></a></li>

        <li class="item">Manager</li>

        <li class="item">List Manager</li>
    </ol>
</div>


<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h3>All Manager</h3>

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}  </strong>
            </div>
            {% endfor %}

        
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">User</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in manager %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}   <img src="{{ x.profile_picture.url }}" width="30" height="30" class="rounded-circle" alt="image"></th>
                        <td>{{ x.user }}</td>
                        <td>{{ x.first_name }}</td>
                        <td>{{ x.last_name }}</td>
                        <td>{{ x.phone }}</td>
                        <td> 
                            <a href="{% url 'admins:edit_manager' x.user.id %}"  data-toggle="tooltip" data-placement="bottom" title="Edit">
                                <i class="bx bxs-edit"></i>
                            </a>
                            
                            <a href="{% url 'admins:delete_manager' x.user.id %}" onclick="return confirm('Are you sure of delete this manager?');"  data-toggle="tooltip" data-placement="bottom" title="Delete">
                                <i class="bx bxs-trash"></i>
                            </a>
                        
                        
                        </td>
                    </tr>
                    {% endfor %}
                   
                </tbody>
            </table>
        </div>

    </div>
</div>
<!-- End -->



{% endblock %}