admins/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import LoginView

app_name = "admins"

urlpatterns = [


    path('index', index, name='index'),

    path('', LoginView.as_view(redirect_authenticated_user=True), name="login"),

    #signup_manager
    path('signup_manager', signup_manager, name='signup_manager'),
    #signup_worker
    path('signup_worker', signup_worker, name='signup_worker'),
    #dashboard
    path('dashboard', dashboard, name='dashboard'),



    #Create Manager
    path('create_manager', create_manager, name='create_manager'),
    # Edit Manager
    url(r'^edit_manager/(?P<id>\d+)/$', edit_manager, name='edit_manager'),
    # Delete Manager
    url(r'^delete_manager/(?P<id>\d+)/$', delete_manager, name='delete_manager'),


    #Create Worker
    path('create_worker', create_worker, name='create_worker'),
    # Edit Worker
    url(r'^edit_worker/(?P<id>\d+)/$', edit_worker, name='edit_worker'),
    # Delete Worker
    url(r'^delete_worker/(?P<id>\d+)/$', delete_worker, name='delete_worker'),



    #Create Departament
    path('create_departament', create_departament, name='create_departament'),
    # Edit Manager
    url(r'^edit_departament/(?P<id>\d+)/$', edit_departament, name='edit_departament'),
    # Delete Departament
    url(r'^delete_departament/(?P<id>\d+)/$', delete_departament, name='delete_departament'),

    

    #List Manager
    path('list_manager', list_manager, name='list_manager'),
    #List Worker
    path('list_worker', list_worker, name='list_worker'),
    #List Departament
    path('list_departament', list_departament, name='list_departament'),


]

pruebas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    
    path('', include('admins.urls')),

    path('manager/', include('manager.urls')),

    path('worker/', include('worker.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worker/urls.py
from . import views
from django.conf.urls import url
from .views import *
from django.urls import path, include

app_name = "worker"

urlpatterns = [


    #Look Tasks
    path('my_tasks', my_tasks, name='my_tasks'),
    # Finish Task
    url(r'^finish_task/(?P<id>\d+)/$', finish_task, name='finish_task'),

    # Create Report
    path('create_report', create_report, name='create_report'),
    # My report
    path('my_report', my_report, name='my_report'),

    # My profile
    path('profile_worker', profile_worker, name='profile_worker'),
   


]

worker/models.py
from django.db import models
from manager.models import Managers, Departament, User
from manager.validators import validate_file_size
from phone_field import PhoneField

class Worker(models.Model):
    manager = models.ForeignKey(Managers, on_delete=models.CASCADE)
    departament = models.ForeignKey(Departament, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    is_active = models.BooleanField(default = False)
    profile_picture = models.ImageField(upload_to='avatar/worker/%Y/%m/%d', default='avatar/default.jpg',
                                 verbose_name='avatar', null=True, blank=True, validators=[validate_file_size])
    ## 
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = PhoneField(blank=True)
    
    def __str__(self):
        return self.first_name + ' ' + self.last_name
    
class Task(models.Model):
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    asign = models.ForeignKey(Managers, on_delete=models.CASCADE)
    #task description
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    #dates
    start_date = models.DateField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    end_date = models.DateField(blank=True, null=True)
    #status
    is_finish = models.BooleanField(default = False)

    def task_complete(self):

        task = Task.objects.filter(worker=self.worker, is_finish=True).count()
        return str(task)
    
    def task_pending(self):

        task = Task.objects.filter(worker=self.worker, is_finish=False).count()
        return str(task)

class Report(models.Model):
    date = models.DateField(auto_now_add=True)
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    observation = models.CharField(max_length=200, blank=True, null=True)

worker/forms.py
from .models import Worker, Task, Report
from django import forms
from manager.models import Managers


class WorkerRegistroForm(forms.ModelForm):

    class Meta:
        model = Worker
        fields = '__all__'
        exclude = ['user', 'is_active']

class WorkerUpdateForm(forms.ModelForm):

    class Meta:
        model = Worker
        fields = '__all__'
        exclude = ['user', 'is_active', 'departament', 'manager']

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__'
        exclude = ['asign']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(TaskForm, self).__init__(*args, **kwargs)
        manager = Managers.objects.get(user=user)
        self.fields['worker'].queryset = Worker.objects.filter(manager=manager)    

class OtherTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['is_finish']
        exclude = ['asign']

class ReportForm(forms.ModelForm):

    class Meta:
        model = Report
        fields = '__all__'
        exclude = ['worker', 'observation']


class ReportUpdateForm(forms.ModelForm):

    class Meta:
        model = Report
        fields = '__all__'
        exclude = ['worker']

        

worker/views.py
from django.shortcuts import render, redirect
from admins.models import User
from django.contrib import messages
from manager.models import Managers, Departament
from django.http import HttpResponseRedirect
from worker.models import *
from worker.forms import *
import datetime
from datetime import datetime, time, date, timedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#task by worker
def my_tasks(request):

    worker = Worker.objects.get(user=request.user)
    task = Task.objects.filter(worker=worker)

    if task:

        porcen_complete = Task.objects.filter(worker=worker, is_finish=True)
        num_complete = porcen_complete.count() * 100 / task.count() 

        porcent_incomplete = Task.objects.filter(worker=worker, is_finish=False)
        num_incomplete = porcent_incomplete.count() * 100 / task.count()

        diference = (porcen_complete.count() -  porcent_incomplete.count()) * 100 / task.count() 

        diference_two = (porcent_incomplete.count() - porcen_complete.count()) * 100 / task.count()
    
    else:
        num_complete = 0
        num_incomplete = 0
        diference = 0
        diference_two = 0


    return render(request, 'worker/task.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#finish task by worker
def finish_task(request, id):
    task = Task.objects.get(id=id)
    today = date.today()

    if request.method == 'POST':
        form = OtherTaskForm(request.POST, instance=task)
        if form.is_valid():
            user = form.save(commit=False)
            user.end_date = today
            user.save()  
            messages.success(request, 'Task has been update successfully')
            return redirect('worker:my_tasks')
    else:
        form = OtherTaskForm(instance=task)
 
    return render(request, 'worker/modal.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#create report / worker
def create_report(request):

    worker = Worker.objects.get(user=request.user)

    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.worker = worker
            user.save()  
            messages.success(request, 'Report has been created successfully')
            return redirect('worker:my_report')
    else:
        form = ReportForm()
 
    return render(request, 'worker/report/create_report.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#list of report by worker
def my_report(request):

    worker = Worker.objects.get(user=request.user)

    report = Report.objects.filter(worker=worker)

    return render(request, 'worker/report/my_report.html', locals())


@login_required(redirect_field_name='/')
@user_passes_test(lambda u: u.is_worker, login_url='admins:dashboard')
#edit profile worker
def profile_worker(request):

    worker = Worker.objects.get(user=request.user)

    if request.method == 'POST':
        form = WorkerUpdateForm(request.POST, instance=worker)
        if form.is_valid():
            user = form.save(commit=False)
            user.worker = worker
            user.save()  
            messages.success(request, 'Profile has been update successfully')
            return redirect('worker:my_report')
    else:
        form = WorkerUpdateForm(instance=worker)
 
    return render(request, 'worker/profile.html', locals())


    

templates/admins/worker/create_worker.html
{% extends "bases/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="breadcrumb-area">
    <h1>Worker</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:index' %}"><i class='bx bx-user-circle'></i></a></li>

        <li class="item">Worker</li>

        {% if worker_user %}
        <li class="item">Edit Worker</li>
        {% else %}
        <li class="item">Add Worker</li>
        {% endif %}
    </ol>
</div>

<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">

        {% if worker_user %}
        <h3>Work Worker</h3>
        {% else %}
        <h3>Add Worker</h3>
        {% endif %}
        
    </div>

    {% if user_form.errors or worker_form.errors  %}
    <br>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ user_form.errors }} </strong>
        <strong>{{ worker_form.errors }} </strong>
    </div>
    {% endif %}
    
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% if worker_user %}
            <div class="form-group">
                {{ worker_form.first_name|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ worker_form.last_name|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ worker_form.phone|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ worker_form.manager|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ worker_form.departament|as_crispy_field }}
            </div>

            <button type="submit" class="btn btn-primary">Edit</button>

            {% else %}

            <div class="form-group">
                {{ user_form.username|as_crispy_field }}
              
            </div>
            <div class="form-group">
                {{ user_form.password1|as_crispy_field }}
              
            </div>
            <div class="form-group">
                {{ user_form.password2|as_crispy_field }}
              
            </div>
            <div class="form-group">
                {{ worker_form.first_name|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ worker_form.last_name|as_crispy_field }}
            </div>
             <div class="form-group">
                {{ worker_form.phone|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ worker_form.manager|as_crispy_field }}
            </div>
            <div class="form-group">
                {{ worker_form.departament|as_crispy_field }}
            </div>


            <button type="submit" class="btn btn-primary">Create</button>

            {% endif %}
            
        </form>

    </div>
</div>


{% endblock %}

templates/admins/worker/list_worker.html
{% extends "bases/base.html" %}


{% block content %}

<div class="breadcrumb-area">
    <h1>Worker</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:dashboard' %}"><i class='bx bx-user-circle'></i></a></li>

        <li class="item">Worker</li>

        <li class="item">List Worker</li>
        
    </ol>
</div>


<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h3>All Worker</h3>

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}  </strong>
            </div>
            {% endfor %}

        
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">User</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Departament</th>
                        <th scope="col">Manager</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in worker %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}   <img src="{{ x.profile_picture.url }}" width="30" height="30" class="rounded-circle" alt="image"></th>
                        <td>{{ x.user }}</td>
                        <td>{{ x.first_name }}</td>
                        <td>{{ x.last_name }}</td>
                        <td>{{ x.phone }}</td>
                        <td>{{ x.departament }}</td>
                        <td>{{ x.manager }}</td>
                        <td> 
                            <a href="{% url 'admins:edit_worker' x.user.id %}"  data-toggle="tooltip" data-placement="bottom" title="Edit">
                                <i class="bx bxs-edit"></i>
                            </a>
                            
                            <a href="{% url 'admins:delete_worker' x.user.id %}" onclick="return confirm('Are you sure of delete this Worker?');"  data-toggle="tooltip" data-placement="bottom" title="Delete">
                                <i class="bx bxs-trash"></i>
                            </a>
                        
                        
                        </td>
                    </tr>
                    {% endfor %}
                   
                </tbody>
            </table>
        </div>

    </div>
</div>
<!-- End -->



{% endblock %}