admins/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import LoginView

app_name = "admins"

urlpatterns = [


    path('index', index, name='index'),

    path('', LoginView.as_view(redirect_authenticated_user=True), name="login"),

    #signup_manager
    path('signup_manager', signup_manager, name='signup_manager'),
    #signup_worker
    path('signup_worker', signup_worker, name='signup_worker'),
    #dashboard
    path('dashboard', dashboard, name='dashboard'),



    #Create Manager
    path('create_manager', create_manager, name='create_manager'),
    # Edit Manager
    url(r'^edit_manager/(?P<id>\d+)/$', edit_manager, name='edit_manager'),
    # Delete Manager
    url(r'^delete_manager/(?P<id>\d+)/$', delete_manager, name='delete_manager'),


    #Create Worker
    path('create_worker', create_worker, name='create_worker'),
    # Edit Worker
    url(r'^edit_worker/(?P<id>\d+)/$', edit_worker, name='edit_worker'),
    # Delete Worker
    url(r'^delete_worker/(?P<id>\d+)/$', delete_worker, name='delete_worker'),



    #Create Departament
    path('create_departament', create_departament, name='create_departament'),
    # Edit Manager
    url(r'^edit_departament/(?P<id>\d+)/$', edit_departament, name='edit_departament'),
    # Delete Departament
    url(r'^delete_departament/(?P<id>\d+)/$', delete_departament, name='delete_departament'),

    

    #List Manager
    path('list_manager', list_manager, name='list_manager'),
    #List Worker
    path('list_worker', list_worker, name='list_worker'),
    #List Departament
    path('list_departament', list_departament, name='list_departament'),


]

pruebas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    
    path('', include('admins.urls')),

    path('manager/', include('manager.urls')),

    path('worker/', include('worker.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admins/departament/create_departament.html
{% extends "bases/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="breadcrumb-area">
    <h1>Departament</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:index' %}"><i class='bx bxs-buildings'></i></a></li>

        <li class="item">Departament</li>

        {% if departament %}
        <li class="item">Edit Departament</li>
        {% else %}
        <li class="item">Add Departament</li>
        {% endif %}
    </ol>
</div>

<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">

        {% if departament %}
        <h3>Update Departament</h3>
        {% else %}
        <h3>Add Departament</h3>
        {% endif %}
        
    </div>

    {% if form.errors  %}
    <br>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ form.errors }} </strong>
    </div>
    {% endif %}
    
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
               {{ form|crispy }}
            </div>
          
            {% if departament %}
            <button type="submit" class="btn btn-primary">Edit</button>
            {% else %}
            <button type="submit" class="btn btn-primary">Create</button>
            {% endif %}
        </form>

    </div>
</div>


{% endblock %}

templates/admins/departament/list_departament.html
{% extends "bases/base.html" %}


{% block content %}

<div class="breadcrumb-area">
    <h1>Departament</h1>

    <ol class="breadcrumb">
        <li class="item"><a href="{% url 'admins:index' %}"><i class='bx bxs-buildings'></i></a></li>

        <li class="item">Departament</li>

        <li class="item">List Departament</li>
    </ol>
</div>


<div class="card mb-30">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h3>All Departament</h3>

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}  </strong>
            </div>
            {% endfor %}

        
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Responsible</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in departament %}
                    <tr>
                        <th scope="row">{{ forloop.counter }} </th>
                        <td>{{ x.name }}</td>
                        <td>{{ x.responsible }}</td>
                        <td> 
                            <a href="{% url 'admins:edit_departament' x.responsible.user.id %}"  data-toggle="tooltip" data-placement="bottom" title="Edit">
                                <i class="bx bxs-edit"></i>
                            </a>
                            
                            <a href="{% url 'admins:delete_departament' x.responsible.user.id %}" onclick="return confirm('Are you sure of delete this departament?');"  data-toggle="tooltip" data-placement="bottom" title="Delete">
                                <i class="bx bxs-trash"></i>
                            </a>
                        
                        </td>
                    </tr>
                    {% endfor %}
                   
                </tbody>
            </table>
        </div>

    </div>
</div>
<!-- End -->



{% endblock %}